language: python
python:
  - "3.4"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
- pytest
- coverage run --source=. -m py.test && coverage report
- coveralls

after_success: coveralls
cache: pip
