"""empty message

Revision ID: 13c592fca965
Revises: 
Create Date: 2017-07-27 20:05:18.483515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13c592fca965'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), server_default='', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('bucket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bucketname', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itemname', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=15), server_default='Not Done', nullable=True),
    sa.Column('bucket_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bucket_id'], ['bucket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.drop_table('bucket')
    op.drop_table('user')
    # ### end Alembic commands ###
